#! /bin/sh

rm -rf /usr/share/themes/okuda/gtk-2.0/*.cache

if [ "`readlink /etc/hildon/theme`" = /usr/share/themes/okuda ]; then
   if [ -x /usr/bin/personalisation ]; then
	   /usr/bin/personalisation /usr/share/themes/default
   fi
fi
